extends Area2D
#ESTE SCRIPT VA A DETECTAR LA COLISION, EN CASO DE QUE EL BIRD CAIGA Y TOQUE EL SUELO, VOY EN MIN 4:30

signal hit

func _on_body_entered(body: Node2D) -> void:
	hit.emit() #JAJAJAJA NO ME LO CREO EL PAJARO NO MORIA AL TOCAR EL SUELO PORQUE SE ME HABIA PASADO
	#PONER EL HIT EMIT AL TOCARLO AQUI
